name: Elihu Bogan
image_dir: /assets/images

theme: jekyll-theme-minimal

title: Elihu Bogan
description: New York and Santa Barbara
logo: /assets/images/headshot.png
show_downloads: false
google_analytics:
